---
spring:
  application:
    name: gateway-service-zuul
  zipkin:
    base-url: http://localhost:8002
    sleuth:
      sampler:
        percentage: 1.0
server:
  port: 8888
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/

zuul:
  AccessFilter:
    pre:
      disable: true
  retryable: true

ribbon:
  MaxAutoRetries: 2
  MaxAutoRetriesNextServer: 0




#zuul:
#  routes:
#    api-a:
#      path: /producer/**
#      service-id: spring-cloud-producer
